### ISSUE TITLE
projectId must be a string in FirebaseApp.options

### ISSUE THREAD

**Issue by krngd2** [bradtraversy/angularfs#1]
I just downloaded and ran `npm i` then replaced firebase config in environment.ts.
When i `ng serve` this error showing up

> ERROR Error: projectId must be a string in FirebaseApp.options
    at new FirestoreError (http://localhost:4200/vendor.bundle.js:16479:28)
    at Function.webpackJsonp.../../../../@firebase/firestore/dist/esm/src/api/database.js.Firestore.databaseIdFromApp (http://localhost:4200/vendor.bundle.js:1094:19)
    at new Firestore (http://localhost:4200/vendor.bundle.js:1001:43)
    at Object.firestore (http://localhost:4200/vendor.bundle.js:12319:76)
    at FirebaseAppImpl.webpackJsonp.../../../../@firebase/app/dist/esm/src/firebaseApp.js.FirebaseAppImpl._getService (http://localhost:4200/vendor.bundle.js:157:66)
    at FirebaseAppImpl.(anonymous function) [as firestore] (http://localhost:4200/vendor.bundle.js:344:31)
    at new AngularFirestore (http://localhost:4200/vendor.bundle.js:20494:30)
    at _getAngularFirestore (http://localhost:4200/vendor.bundle.js:20542:12)
    at _callFactory (http://localhost:4200/vendor.bundle.js:77527:20)
    at _createProviderInstance$1 (http://localhost:4200/vendor.bundle.js:77477:26)

**Comment by andrewpat24** [comment]
@krngd2 did you ever find a solution to this?

**Comment by krngd2** [comment]
> @krngd2 did you ever find a solution to this?

No

**Comment by andrewpat24** [comment]
All good! I ended up just deleting my repo and re-cloning. Not ideal but.. whatever.
